// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMGKzjFu3hGOmteDOqyenR_ItSdGVc2o0',
    appId: '1:1058004726410:android:79ff1f6f84ac1dadd6f373',
    messagingSenderId: '1058004726410',
    projectId: 'holobox-b7d56',
    storageBucket: 'holobox-b7d56.firebasestorage.app',
  );

  // TODO: Replace these values with your iOS app's config from Firebase Console
  // Go to: Firebase Console → Project Settings → Your apps → Holobox Admin iOS

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5nSCixFSWfdjhNrG6IRWlLgHuum2tyA',
    appId: '1:1058004726410:ios:2d57fe43332511bad6f373',
    messagingSenderId: '1058004726410',
    projectId: 'holobox-b7d56',
    storageBucket: 'holobox-b7d56.firebasestorage.app',
    iosBundleId: 'com.holobox.iosadmin',
  );

  // Copy the values from the downloaded GoogleService-Info.plist
}